---
- name: install virtualenv
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "virtualenv"
    - "python-setuptools"
  when: ansible_distribution == 'Ubuntu'

- name: create location for python virtual env
  file:
    path: "{{ deepops_dir }}"
    state: directory
  when: ansible_distribution == 'Ubuntu'

- name: install openshift python client for k8s_raw module
  pip:
    name: openshift
    virtualenv: "{{ deepops_venv }}"
  when: ansible_distribution == 'Ubuntu'

- name: install openshift python client for k8s_raw module
  yum:
    name: python2-openshift
  when: ansible_os_family == 'RedHat'

- name: create GPU device plugin
  k8s:
    state: present
    definition: "{{ lookup('url', nvidia_k8s_device_plugin_def, split_lines=False) }}"
  run_once: true
  environment:
    PYTHONHOME: '{{ deepops_venv }}'
  when: ansible_distribution == 'Ubuntu'

- name: create GPU device plugin
  k8s:
    state: present
    definition: "{{ lookup('url', nvidia_k8s_device_plugin_def, split_lines=False) }}"
  run_once: true
  when: ansible_os_family == 'RedHat'
