---
collections:

- name: ansible.posix
  version: 1.1.1

- name: community.general
  version: 4.7.0

- name: community.docker
  version: 2.3.0

roles:

- src: dev-sec.ssh-hardening
  version: "6.1.3"

- src: https://github.com/DeepOps/ansible-role-users
  name: DeepOps.users
  version: 'e67df1db28bf099aa06d0ab250478963532b4d29'

- src: https://github.com/DeepOps/ansible-role-hosts.git
  version: 'c21a676088c07db3db3ac9332cf584eeb068e3fd'
  name: DeepOps.hosts

- src: geerlingguy.ntp
  version: "1.6.3"

- src: andrewrothstein.miniconda
  version: "v5.2.6"

- src: nvidia.nvidia_driver
  version: "v2.2.1"

- src: nvidia.nvidia_docker
  version: "v1.2.4"

- src: nvidia.enroot
  version: "v0.5.0"

- src: geerlingguy.filebeat
  version: "3.3.0"

- src: robertdebock.java
  version: "4.1.1"

- src: robertdebock.elastic_repo
  version: "1.0.3"

- src: robertdebock.logstash
  version: "1.1.1"

- src: robertdebock.elasticsearch
  version: "1.1.3"

- src: robertdebock.kibana
  version: "1.2.4"

- src: https://github.com/DeepOps/ansible-maas.git
  name: ansible-maas
  version: '632fe9bd1e048b9abb717621dc2d76b19614327b'

- src: https://github.com/DeepOps/ansible-role-chrony
  name: DeepOps.chrony
  version: 'c9022153036dfdde4e2b313aecde4a46cd6f6687'

- src: https://github.com/OSC/ood-ansible.git
  version: 'v2.0.3'

- src: abims_sbr.singularity
  version: 3.7.1-1

- src: gantsign.golang
  version: 2.4.0
