---

- src: dev-sec.ssh-hardening
  version: "6.1.3"

- src: https://github.com/DeepOps/ansible-role-users
  name: DeepOps.users
  version: 'e67df1db28bf099aa06d0ab250478963532b4d29'

- src: https://github.com/DeepOps/ansible-role-hosts.git
  version: '8311d6ecfe39b665a06d1fc55502c6916e9ab5ce'
  name: DeepOps.hosts

- src: geerlingguy.ntp
  version: "1.6.3"

- src: andrewrothstein.miniconda
  version: "v5.2.6"

- src: nvidia.nvidia_driver
  version: "v2.0.0"

- src: nvidia.nvidia_docker
  version: "v1.2.1"

- src: https://github.com/NVIDIA/ansible-role-enroot.git
  version: "v0.3.2"

- src: geerlingguy.filebeat
  version: "2.0.1"

- src: geerlingguy.logstash
  version: "4.0.0"

- src: geerlingguy.elasticsearch
  version: "3.0.1"

- src: geerlingguy.java
  version: "1.9.5"

- src: geerlingguy.kibana
  version: "3.2.1"

- src: https://github.com/DeepOps/ansible-maas.git
  name: ansible-maas
  version: '632fe9bd1e048b9abb717621dc2d76b19614327b'

- src: https://github.com/DeepOps/ansible-role-chrony
  name: DeepOps.chrony
  version: 'c9022153036dfdde4e2b313aecde4a46cd6f6687'

- src: https://github.com/OSC/ood-ansible.git
  version: 'a56783750d5e61f0d099a2b294d9f050d194f293'

- src: gantsign.golang
  version: 2.4.0

- src: lecorguille.singularity
  version: 1.2.0
