# Vars needed to install nfs-client-provisioner
k8s_nfs_server: "127.0.0.1"
k8s_nfs_export_path: "/export/deepops_nfs"
k8s_nfs_default_sc: "true"
k8s_nfs_client_repo_name: "nfs-subdir-external-provisioner"
k8s_nfs_client_helm_repo: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"
k8s_nfs_client_chart_name: "{{ k8s_nfs_client_repo_name }}/nfs-subdir-external-provisioner"
k8s_nfs_client_release_name: "nfs-subdir-external-provisioner"
k8s_nfs_client_chart_version: "4.0.13"
