---

- name: Remove firmware container image
  command: "docker rmi -f {{ firmware_update_repo }}:{{ firmware_update_tag }}"
  ignore_errors: yes

- name: Remove firmware image tarbal
  command: "rm {{ fw_dir}}/{{ firmware_update_container }}"
  ignore_errors: yes

# nvsm does not allow you to specify a dump location, so we search /tmp for the last dump
- name: Get name of the latest dumpfile from nvsm
  shell: "ls -taA1 /tmp | grep nvsm-health.*tar.* | head -n 1"
  register: nvsm_dump_file
  ignore_errors: yes

- name: Remove dump tarball
  shell: "rm /tmp/{{ nvsm_dump_file.stdout }}"
  ignore_errors: yes

- name: Remove diagnostic directory
  command: "rm -rf {{ fw_dir }}"

