---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mofed-ubuntu-2004
    image: geerlingguy/docker-ubuntu2004-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true
  - name: mofed-ubuntu-2204
    image: geerlingguy/docker-ubuntu2204-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  ansible_args:
  - -vv
  inventory:
    group_vars:
      all:
        mofed_install_flags: "--all --without-fw-update --user-space-only"
verifier:
  name: ansible
