---

- name: add cgroups to grub options
  lineinfile:
    dest: /etc/default/grub
    insertafter: '^GRUB_CMDLINE_LINUX=[^\\$]'
    line: 'GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} cgroup_enable=memory swapaccount=1"'
  register: update_grub

- name: update grub
  block:
    - command: update-grub
    - file:
        path: /var/run/reboot-required
        state: touch
  when: update_grub.changed

- name: create slurm directories
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    mode: 0755
  with_items:
    - /etc/slurm
    - /var/log/slurm
    - /var/spool/slurm/d

- name: copy slurmdbd service file
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - slurmd.service

- name: create prolog.d directory
  file:
    path: /etc/slurm/prolog.d/
    state: directory
    owner: slurm
    group: slurm
    mode: 0755
  tags:
    - prolog

- name: create epilog.d directory
  file:
    path: /etc/slurm/epilog.d/
    state: directory
    owner: slurm
    group: slurm
    mode: 0755
  tags:
    - epilog

- name: copy prologs
  copy:
    src: "{{ item }}"
    dest: /etc/slurm/prolog.d/
    owner: slurm
    group: slurm
    mode: 0755
  with_fileglob:
    - prolog.d/*
  tags:
    - prolog

- name: copy epilogs
  copy:
    src: "{{ item }}"
    dest: /etc/slurm/epilog.d/
    owner: slurm
    group: slurm
    mode: 0755
  with_fileglob:
    - epilog.d/*
  tags:
    - epilog

- name: copy configuration files
  template:
    src: "{{ item }}"
    dest: "/etc/slurm/{{ item }}"
  with_items:
    - slurm.conf
    - cgroup.conf
    - gres.conf
  notify:
    - restart slurmd
  tags:
    - config

- name: start slurmd
  systemd:
    name: slurmd
    state: started
    enabled: yes
    daemon-reload: yes

- name: install /etc/localusers
  template:
    src: etc-localusers
    dest: /etc/localusers
    mode: 0600
  tags:
    - test

- name: update /etc/pam.d/sshd
  lineinfile:
    path: /etc/pam.d/sshd
    line: "account required pam_listfile.so item=user sense=allow file=/etc/localusers"
    insertafter: "PAM configuration for the Secure Shell service"
    state: present
  tags:
    - test

- name: update /etc/pam.d/sshd
  lineinfile:
    path: /etc/pam.d/sshd
    line: "account sufficient /usr/lib/pam_slurm.so"
    insertafter: "PAM configuration for the Secure Shell service"
    state: present
  tags:
    - test
