---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: krb-ubuntu-2204
    image: geerlingguy/docker-ubuntu2204-ansible
    cgroupns_mode: host
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  ansible_args:
  - -vv
  inventory:
    group_vars:
      all:
        kerberos_client_realm_name: "example.com"
verifier:
  name: ansible
