---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: krb-ubuntu-2004
    image: geerlingguy/docker-ubuntu2004-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    tmpfs:
    - /run
    - /tmp
    pre_build_image: true
  - name: krb-ubuntu-2204
    image: geerlingguy/docker-ubuntu2204-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    tmpfs:
    - /run
    - /tmp
    pre_build_image: true
provisioner:
  name: ansible
  ansible_args:
  - -vv
  inventory:
    group_vars:
      all:
        kerberos_client_realm_name: "example.com"
verifier:
  name: ansible
