---
- name: restart nfs
  service: name=nfs-kernel-server state=restarted
  when: ansible_os_family == "Debian"

- name: restart nfs
  service: name=nfs-server state=restarted
  when: ansible_os_family == "RedHat"
