- name: check if driver already installed
  command: nvidia-smi
  register: nvidia_smi
  ignore_errors: true

- name: include install tasks
  include_tasks: install.yml
  when: nvidia_smi.rc != 0 or reinstall_nvidia_driver
