# sudo docker run --rm -ti --net=host --privileged -v /mnt/:/iso:ro -e HOST_INT_PUB=ens160 -e HOST_INT_PRV=ens192 -e DEFAULT=DGX --name dgxie dgxie
# sudo docker run -d --name nfs --privileged --net=host -v /home/ubuntu/:/master -e SHARED_DIRECTORY=/master nfs-server:latest
version: '3'
services:
    dgxie:
        build: .
        network_mode: "host"
        privileged: true
        volumes:
            - /mnt/4.1.0:/iso:ro
            - ./config/containers/dgxie/machines:/etc/machines:ro
        environment:
            - HOST_INT_PUB=eth0
            - HOST_INT_PRV=eth1
            - DEFAULT=DGX
            #- IP=192.168.1.1
            #- NETWORK=192.168.1.0
            #- NETMASK=255.255.255.0
            #- GATEWAY=192.168.1.1
            #- DNS1=8.8.8.8
            #- DNS2=8.8.4.4
            #- DHCP_START=192.168.1.2
            #- DHCP_END=192.168.254
