---
- name: ensure mountpoint exists
  file:
    path: '{{ item.mountpoint }}'
    state: directory
    mode: "0755"
  with_items: '{{ nfs_mounts }}'
  when: nfs_mounts|length
  tags:
    - nfs

- name: configure /etc/fstab on clients
  mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.server }}:{{ item.path }}"
    opts: "{{ item.options }}"
    fstype: nfs 
    state: mounted
  with_items: '{{ nfs_mounts }}'
  when: nfs_mounts|length
  tags:
    - nfs

- name: rhel | install management prereq
  yum:
    name: "python3-libsemanage"
    state: present
  when: ansible_os_family == "RedHat"

- name: rhel | enable nfs home directory usage
  seboolean:
    name: "use_nfs_home_dirs"
    state: yes
    persistent: yes
  when: ansible_os_family == "RedHat"
