---
- hosts: kube_control_plane
  become: true
  tasks:
    - name: Install helm chart for container registry
      include_role:
        name: k8s-internal-container-registry
      run_once: true
  tags:
    - container-registry

- hosts: kube_node
  become: true
  vars:
    container_registry_hostname: registry.local
  tasks:
    - name: Set registry hostname in /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[groups['kube_control_plane'][0]]['ansible_host'] | default(hostvars[groups['kube_control_plane'][0]]['ansible_default_ipv4']['address']) }} {{ container_registry_hostname }}"
  tags:
    - container-registry
