---
- name: Ensure OpenShift packages are installed
  import_playbook: ../bootstrap/bootstrap-openshift.yml

# GPU operator
- hosts: kube_control_plane[0]
  become: yes
  tasks:
    - name: Install helm chart for GPU operator
      include_role:
        name: nvidia-gpu-operator
      run_once: true
  environment: "{{proxy_env if proxy_env is defined else {}}}"
  tags:
    - nvidia
    - nvidia-gpu-operator
