---
## Playbook for installing nvidia-network-operator
#
- hosts: kube_control_plane[0]
  become: true
  become_method: sudo
  tasks:
    - include_role:
        name: nvidia-network-operator
        tasks_from: main
