# Package version pinning
nvidia_docker2_package_version: ''
nvidia_container_runtime_package_version: ''

docker_daemon_json:
  runtimes:
    nvidia:
      path: /usr/bin/nvidia-container-runtime
      runtimeArgs: []

nvdocker_repo_base_url: "https://nvidia.github.io/nvidia-docker"
nvdocker_gpg_path: "{{ nvdocker_repo_base_url }}/gpgkey"

nvidia_docker_wrapper_url: https://raw.githubusercontent.com/NVIDIA/nvidia-docker/master/nvidia-docker
