- name: add users
  hosts: all
  become: true
  roles:
    - { role: users, tags: users }

  #- name: gen ssh keys
  #hosts: slurm-masters
  #become: true
  #roles:
  #- { role: users, is_controller: yes }
