---
- name: install virtualenv and setuptools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "virtualenv"
    - "python3-setuptools"
  when: ansible_distribution == 'Ubuntu'
  environment: "{{proxy_env if proxy_env is defined else {}}}"

- name: create location for deepops files
  file:
    path: "{{ deepops_dir }}"
    state: directory

- name: install openshift python client for k8s_raw module
  pip:
    name: openshift
    virtualenv: "{{ deepops_venv }}"
  when: ansible_distribution == 'Ubuntu'
  environment: "{{proxy_env if proxy_env is defined else {}}}"

- name: trust GPG key for EPEL
  rpm_key:
    key: "{{ epel_key_url }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: install EPEL for CentOS
  yum:
    name: "{{ epel_package }}"
  when: ansible_os_family == "RedHat"

  # TODO: Verify that RHEL  does not require venv
- name: install openshift python client for k8s_raw module
  yum:
    name: python2-openshift
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "7"
  environment: "{{proxy_env if proxy_env is defined else {}}}"

- name: install openshift python client for k8s_raw module
  yum:
    name: python3-openshift
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "8"
  environment: "{{proxy_env if proxy_env is defined else {}}}"
