---
- hosts: all
  become: yes
  tasks:
    - name: set /etc/hostname
      hostname:
        name: "{{ inventory_hostname }}"
      when: "{{ deepops_set_hostname | default(true) }}"

    - name: set /etc/hosts
      include_role:
        name: DeepOps.hosts
      vars:
        hosts_add_ansible_managed_hosts: true
