---
- name: restart nis
  service: name=ypbind state=restarted enabled=yes
  when: (ansible_os_family == "Debian" and ansible_distribution_version in [ "14.04" ])

- name: restart nis
  service: name=nis state=restarted enabled=yes
  when: ansible_os_family == "RedHat"
