---
kerberos_client_redhat_pkg:
  - libselinux-python
  - krb5-libs
  - krb5-workstation
  - cyrus-sasl-gssapi

kerberos_client_ubuntu_pkg:
  - python-selinux
  - krb5-user
  - libsasl2-modules-gssapi-mit
  - libpam-krb5
