---
# playbook for VF activation after installing  Mellanox OFED
#
# Author: Vitaliy Razinkov <vitaliyra@mellanox.com>
#

- name: "Check activation"
  register: result
  shell: "grep -i {{ item }} /etc/rc.local"
  failed_when: result.rc == 2


- name: VF activation
  shell: |
    echo 8 > /sys/class/net/{{ item }}/device/sriov_numvfs
    sed -i '/^exit 0*/i echo 8 > /sys/class/net/{{ item }}/device/sriov_numvfs' /etc/rc.local
  when: result.rc > 0

