config:
  BinderHub:
    use_registry: false
    # image_prefix: <docker-id|organization-name>/<prefix>- # Used to name docker images if use_registry is true
    # hub_url: 

# Require 1 GPU for each Notebook deployment
jupyterhub:
  singleuser:
    extraResource:
      guarantees:
        nvidia.com/gpu: "1"
      limits:
        nvidia.com/gpu: "1"
  cull:
    enabled: true
    timeout: 3600 # Delete Pods that have been inactive for over n seconds
    every: 600 # Check for inactive Pods ever n seconds

# Depending on how you have your Docker networking setup, Docker in Docker may be required to reach the Internet during Docker builds.
# It is recommended to enable this. Doing so will launch an additional dind pod to help in this process.
dind:
  enabled: true
