# See the github repo for more details:  https://github.com/helm/charts/blob/master/stable/dask/values.yaml
# For best results, use the same docker image for workers and schedulers

# Specify the resources used for each worker as well as the number of workers.
worker:
  image:
    # repository: nvcr.io/nvidia/rapidsai/rapidsai
    repository: dask-rapids
    tag: latest
    env:
  replicas: 1
  resources: 
    requests:
      nvidia.com/gpu: 1
    limits:
      nvidia.com/gpu: 1

scheduler:
  image:
    repository: dask-rapids
    tag: latest

# By default we should be doing all Dask works on workers using calls to distributed.Client()
# If you would like to run/test your GPU code without using workers you may comment the resources section
jupyter:
  image:
    repository: dask-rapids
    tag: latest
  resources: 
    requests:
      nvidia.com/gpu: 0
    limits:
      nvidia.com/gpu: 0
