---
- hosts: "{{ hostlist | default('all') }}"
  become: true
  become_method: sudo
  tags:
  - docker
  vars_files:
    # include kubespray-defaults here so that we can set the facts using the
    # kubespray 0020-set_facts.yml tasks
    - ../../submodules/kubespray/roles/kubespray-defaults/defaults/main/main.yml
    - ../../submodules/kubespray/roles/kubernetes/preinstall/defaults/main.yml
  tasks:
    - name: include kubespray task to set facts required for docker role
      include_tasks: ../../submodules/kubespray/roles/kubernetes/preinstall/tasks/0020-set_facts.yml
      when: docker_install | default('yes')
    - name: remove docker overrides, specifically to deal with conflicting options from DGX OS
      file:
        path: /etc/systemd/system/docker.service.d/docker-override.conf
        state: absent
      when: docker_install | default('yes')

- hosts: "{{ hostlist | default('all') }}"
  become: true
  become_method: sudo
  tags:
  - docker
  vars:
    fallback_ips: []
  roles:
    - role: kubespray-defaults
      when: docker_install | default('yes')
    - role: "../../submodules/kubespray/roles/container-engine/docker"
      when: docker_install | default('yes')
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
