---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Check for DGX packages
      stat:
        path: /etc/dgx-release
      register: is_dgx

    - name: create docker config directory
      file:
        path: /etc/docker
        state: directory

    - name: write new docker config
      copy:
        content: "{{ docker_daemon_json | to_nice_json }}"
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
      when:
        - is_dgx.stat.exists == False

    - name: install docker
      include_role:
        name: docker
      vars:
        # matches: kubespray/roles/container-engine/docker/vars/ubuntu-amd64.yml
        docker_package: 'docker-ce=5:18.09.7~3-0~ubuntu-{{ ansible_distribution_release|lower }}'
      when:
        - ansible_distribution == "Ubuntu"
        - is_dgx.stat.exists == False
      environment: "{{proxy_env if proxy_env is defined else {}}}"

    - name: install docker
      include_role:
        name: docker
      vars:
        # matches: kubespray/roles/container-engine/docker/vars/redhat.yml
        # override deprecated dockerproject repo; old docker repo broken as of 03.04.2020
        dockerproject_rh_repo_base_url: 'https://download.docker.com/linux/centos/7/$basearch/stable'
        dockerproject_rh_repo_gpgkey: 'https://download.docker.com/linux/centos/gpg'
        docker_package: 'docker-ce-18.09.7-3.el7'
      when:
        - ansible_os_family == "RedHat"
        - is_dgx.stat.exists == False
      environment: "{{proxy_env if proxy_env is defined else {}}}"
