---
- hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: create docker config directory
      file:
        path: /etc/docker
        state: directory

    - name: write new docker config
      copy:
        content: "{{ docker_daemon_json | to_nice_json }}"
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644

    - name: install docker
      include_role:
        name: docker
      vars:
        # matches: kubespray/roles/container-engine/docker/vars/ubuntu-amd64.yml
        #docker_package: 'docker-ce=18.06.1~ce~3-0~ubuntu'
        docker_package: 'docker-ce=5:18.09.5~3-0~ubuntu-{{ ansible_distribution_release }}'
      when: ansible_distribution == "Ubuntu"

    - name: install docker
      include_role:
        name: docker
      vars:
        # matches: kubespray/roles/container-engine/docker/vars/redhat.yml
        #docker_package: 'docker-ce-18.06.2.ce-3.el7'
        docker_package: 'docker-ce-18.09.5-3.el7'
      when: ansible_os_family == "RedHat"
