# Have to manually remove for now to downgrade:
# sudo apt-get -y remove cuda-drivers cuda-drivers-diagnostic libcuda1-390 nvidia-390 nvidia-390-dev nvidia-390-diagnostic nvidia-modprobe nvidia-opencl-icd-390 nvidia-settings
- hosts: all #dgx-servers
  become: true
  become_method: sudo
  vars:
    use_internal_repo: true
    use_latest_gpu_driver: true
    driver_version: 418.31-0
    apt_key_url: http://cuda-repo/repos/r10.1/official/ubuntu1804/x86_64/7fa2af80.pub
    apt_key_id: 7FA2AF80
    apt_repo_url: http://cuda-repo/repos/r10.1/official/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.94-1_amd64.deb
    apt_repo_name: cuda-repo-ubuntu1804=10.1.94-1
  roles:
    - gpu-driver
