---
# Ensure OpenShift packages are installed
- include: bootstrap-openshift.yml

# Prepare compute nodes for GPU operator
- hosts: kube-node
  become: yes
  tasks:
    - name: node prep for GPU operator
      include_role:
        name: nvidia-gpu-operator-node-prep
  tags:
    - nvidia
    - nvidia-gpu-operator

# GPU operator
- hosts: kube-master
  become: yes
  tasks:
    - name: Install helm chart for GPU operator
      include_role:
        name: nvidia-gpu-operator
      run_once: true
  tags:
    - nvidia
    - nvidia-gpu-operator
