---
- name: Ubuntu | install CUDA keyring
  apt:
    deb: "{{ nvidia_driver_ubuntu_cuda_keyring_url }}"
    state: "present"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Ubuntu | force apt update
  apt:
    update_cache: true
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  changed_when: false

- name: Ubuntu | install package
  apt:
    name: "{{ dcgm_pkg_name }}"
    state: "present"
